# Generated by Django 5.2.8 on 2025-11-09 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('slots', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=20)),
                ('creation_time', models.DateTimeField()),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('commented_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.station')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=20)),
                ('creation_time', models.DateTimeField()),
                ('replier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.comment')),
            ],
        ),
        migrations.CreateModel(
            name='StationStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('empty_slots', models.IntegerField()),
                ('free_bikes', models.IntegerField()),
                ('empty', models.BooleanField()),
                ('full', models.BooleanField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.station')),
            ],
        ),
    ]
